### ISSUE TITLE
Linked transactions are not visible on a material sample

### ISSUE THREAD

**Issue by nadinetamm** [DINA-Web/collection-specs#159]
Currently, selected transactions cannot be seen directly on a material sample. A list of selected material samples can only be viewed when a transaction is called up directly.

<img width="1324" alt="transaction_module" src="https://user-images.githubusercontent.com/115980888/222573147-5bc63e91-c522-4aa3-ae7f-da5d72025705.png">

<img width="2455" alt="material_sample_640b1cd4-715e-4583-b5ee-d2a96e1dc138" src="https://user-images.githubusercontent.com/115980888/222573157-a4c8317a-da69-469e-b938-6fc42824a0d4.png">

**Comment by cgendreau** [comment]
Done as per dina-ui 0.120

**Comment by nadinetamm** [comment]
Thanks for the implementation. Currently we can only see one _transaction_ per material sample, but some material samples have several transactions.

<img width="2106" alt="transaction_materialsample" src="https://user-images.githubusercontent.com/115980888/228526726-51ef7f3c-dcbf-4097-af08-06ca87f76a0b.png">
