### ISSUE TITLE
How to share/identify a material sample? Link does not work?

### ISSUE THREAD

**Issue by nadinetamm** [DINA-Web/collection-specs#160]
We complemented _scheduled actions_ with a reminder function via e-mail. Currently we cannot refer to the concerned _material sample_ in our e-mail: The problem at the moment is that our existing _material samples_ do not have a _mandatory Primary ID_. Is there a way to share a material sample?

**Comment by cgendreau** [comment]
It should be shared by uuid .

`/collection/material-sample/view?id=7c211379-6af7-4f4f-8e6a-0534739e065c`

**Comment by nadinetamm** [comment]
Thanks, it worked, we found the problem on our system.
