### ISSUE TITLE
Managed Attributes in Preparations

### ISSUE THREAD

**Issue by nadinetamm** [DINA-Web/collection-specs#167]
We still need managed attributes in the Preparations section, you said you could help with this: 

"I would not recommend that route to add a managed attribute related to the preparation (a managed-attribute to the material-sample related to its preparation to be exact). A regular managed attribute with the component set to Preparation would do the work. We can help with that."

**Comment by cgendreau** [comment]
API done in https://github.com/AAFC-BICoE/natural-history-collection-api/releases/tag/v0.73.
Specification updated by https://github.com/DINA-Web/collection-specs/commit/f8620c58ac57bba8d4511f8ecc7826b1da13ced7

A Pull Request for the user interface can be submitted on https://github.com/AAFC-BICoE/dina-ui

**Comment by nadinetamm** [comment]
Thanks, Jan takes care of the missing frontend implementation.
