### ISSUE TITLE
Definitions for model components

### ISSUE THREAD

**Issue by cboelling** [DINA-Web/collection-specs#27]
I ask that the definitions in the [Readme.md](https://github.com/DINA-Web/collection-specs/blob/master/README.md) of this repo are updated with definitions for any term used for specifying model components. I find the current definitions confusing (and also somewhat cursory) as they refer to representations of the entities in question rather than their attributes.

For example, the current definition of **Collecting Event** is

**Data associated with the collecting of the specimen(s) at a given time and place.**

whereas I would (tentatively, subject to further refinement by whatever is deemed characteristic of a collecting event) define it as:

**A collecting event is an event in which a material sample is collected.**

deferring any ambiguity just to what an "event" or "material sample" denotes.

Otherwise I find it hard to understand if issues like #25 are just a terminological issue or something that requires structural amendments so it can be represented.

Proposed definitions could be discussed in this thread or in separate issues.

**Comment by cgendreau** [comment]
Sure, definitions in the README are a starting point and there is no doubt they should be refined and expanded (that's why there are in the readme and not in a glossary yet). For taxonomy we had a [glossary](https://github.com/DINA-Web/dina-use-cases/blob/master/glossary.md) and I would like us to have a similar file for collection (the format, not necessarily the content).

**Comment by jmacklin** [comment]
Yes, we need to separate the definitions referring directly to the model that are essentially relationship-based from the definitions used to explain what a collecting event or material sample is to others. I think we also want to use terms in the data model that are clear/clean in the sense of their function and potentially use "synonymous" terms that are familiar to biologists when involving them (e.g., the DarwinCore terms and definitions)...

**Comment by cgendreau** [comment]
The initla [glossary](https://github.com/DINA-Web/collection-specs/blob/master/documentation/glossary.md) is now available so you can send Pull Request to suggest modifications/additions.
