### ISSUE TITLE
Ability to store and update PHAC Risk Group (RG) and Containment Level

### ISSUE THREAD

**Issue by ssbilkhu** [DINA-Web/collection-specs#29]
Ability to store and update PHAC Risk Group (RG) and Containment Level.  SeqDB currently tracks these fields and I believe we have a script to update specimen records based on taxonomic matching.

**Comment by jmacklin** [comment]
This is an interesting case as the regulations influence storage/preparations. I think we need some specific use case for how this information needs to be incorporated into a workflow. This will be most impactful on the living fungal collections (CCFC). The script could flag taxa that are on the list to inform users. This would be especially relevant to transactions. Also, at the time a specimen is received/accessioned a user would want to know this taxon is regulated as it would impact preparation/storage. Could the lists be stored similarly to vocabularies that would populate a drop-down field? Discovery would be done in the reporting tool and potentially the portal.

**Comment by cgendreau** [comment]
Done using field extensions + config file
