### ISSUE TITLE
Improved specimen linkage between collections 

### ISSUE THREAD

**Issue by ssbilkhu** [DINA-Web/collection-specs#30]
If a specimen record has been given to another lab or collection we would like to link between permanent collections and working collections and other use cases like P to P or W to W.

**Comment by jmacklin** [comment]
It is the specimen itself that would be transferred potentially involving a change in the preparation. This is essential as some portion of working collections will be transferred to the permanent collections and we want to maintain the link as the researcher may annotate the identification/determination or improve the metadata of the event and this data should be updated in the permanent collection record.
