### ISSUE TITLE
Ability to name the specimens and their associated data according to a logical nomenclature that captures their history

### ISSUE THREAD

**Issue by ssbilkhu** [DINA-Web/collection-specs#32]
THis is another request from the Franck Stefani Lab's OPF.

Ability to name the specimens and their associated data according to a logical nomenclature that captures their history. 

Currently SeqDB uses a mix of letters and numbers.  Franck would like to use a different system.

**Comment by jmacklin** [comment]
This use case needs to be much more detailed. Provenance is an important aspect of the model and we should not be relying on human-readable identifiers within the system to accomplish this. I would suggest this is moved to the Search module.
