### ISSUE TITLE
Ability to show on a map the geographic origin of the mixed specimens

### ISSUE THREAD

**Issue by ssbilkhu** [DINA-Web/collection-specs#33]
Another request from the Franck Stefani Lab's OPF.

Ability to show on a map the geographic origin of the mixed specimens.  This feature request might actually below in the reports module, not here in collection-specs

**Comment by jmacklin** [comment]
Agreed. This functionality is discovery-based and should be done as a report within the CMS or from the external-facing portal. Suggest move to reporting module.
