### ISSUE TITLE
Create draft Open API 3 file for Collecting Event

### ISSUE THREAD

**Issue by cgendreau** [DINA-Web/collection-specs#35]
Current use cases: https://github.com/DINA-Web/dina-model-concepts/issues?q=is%3Aissue+is%3Aopen+label%3A%22component%3A+collecting-event%22

Draft should cover requirements 13 to 17.

**Comment by xuemeigan** [comment]
Questions, documentation will be a reference to a file stored in minio?
agent and materialSample will be referring to another entity, hence they will both be type uuid?
location can be an array of 2 floats for longitude and latitude?

**Comment by cgendreau** [comment]
What `documentation ` is referring to? If it's related to Issue #10 , indeed, it will point to a record in the object-store.

collectingAgent (#4) is also a link to the agent module, `materialSample `is out-of-scope for that issue.

[DarwinCore terms](https://dwc.tdwg.org/terms/) should be used when possible.


* [decimalLatitude](https://dwc.tdwg.org/terms/#dwc:decimalLatitude)
* [decimalLongitude](https://dwc.tdwg.org/terms/#dwc:decimalLongitude)
